from __future__ import annotations

import platform
import shutil
import subprocess
import sys
from pathlib import Path

from _common import REPORTS_DIR, ROOT, ensure_dirs


def run_capture(args: list[str]) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            args,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=30,
            check=False,
        )
        return proc.returncode, proc.stdout.strip()
    except FileNotFoundError:
        return 127, f"Command not found: {args[0]}"
    except subprocess.TimeoutExpired:
        return 124, f"Command timed out: {' '.join(args)}"


def python_torch_report() -> str:
    code = (
        "import json, sys\n"
        "info={'python': sys.version.split()[0]}\n"
        "try:\n"
        " import torch\n"
        " info['torch']=torch.__version__\n"
        " info['cuda_available']=torch.cuda.is_available()\n"
        " info['cuda_version']=torch.version.cuda\n"
        " if torch.cuda.is_available():\n"
        "  info['gpu_name']=torch.cuda.get_device_name(0)\n"
        "  props=torch.cuda.get_device_properties(0)\n"
        "  info['gpu_total_gb']=round(props.total_memory/1024**3,2)\n"
        "except Exception as e:\n"
        " info['torch_error']=repr(e)\n"
        "print(json.dumps(info, ensure_ascii=False, indent=2))\n"
    )
    _, out = run_capture([sys.executable, "-c", code])
    return out


def main() -> None:
    ensure_dirs()
    total, used, free = shutil.disk_usage(ROOT)
    nvidia_code, nvidia_out = run_capture(["nvidia-smi"])
    report = f"""# Environment Report

Generated by `scripts/env_check.py`.

## System

- platform: `{platform.platform()}`
- python_executable: `{sys.executable}`
- workspace: `{ROOT}`
- disk_total_gb: `{total / 1024**3:.1f}`
- disk_free_gb: `{free / 1024**3:.1f}`

## Python / PyTorch

```json
{python_torch_report()}
```

## NVIDIA

- nvidia_smi_exit_code: `{nvidia_code}`

```text
{nvidia_out}
```

## Cache Directories

- data_dir: `{ROOT / "data"}`
- model_dir: `{ROOT / "models"}`
- runs_dir: `{ROOT / "runs"}`
- results_dir: `{ROOT / "results"}`

## Notes

- If visible GPU memory is not the expected 16GB, fix driver/device recognition before full TSFM experiments.
- This check does not download models or datasets.
"""
    out_path = REPORTS_DIR / "env_report.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()

